-
@expo-google-fonts/tajawal
@expo/vector-icons
@react-native-community/clipboard
@react-native-masked-view/masked-view
@react-navigation/bottom-tabs
@react-navigation/material-top-tabs
@react-navigation/native
@react-navigation/native-stack
@reduxjs/toolkit
@twotalltotems/react-native-otp-input
axios
data-uri-to-blob
dotenv
expo-app-loading
expo-constants
expo-dev-client
expo-document-picker
expo-font
expo-image-picker
expo-localization
expo-notifications
expo-secure-store
expo-splash-screen
expo-updates
firebase
formik
i18next
native-base
react-i18next
react-native-gesture-handler
react-native-image-resizer
react-native-image-to-blob
react-native-keyboard-aware-scroll-view
react-native-maps
react-native-masked-view
react-native-pager-view
react-native-phone-number-input
react-native-reanimated
react-native-safe-area-context
react-native-screens
react-native-svg
react-native-tab-view
react-native-web
react-navigation
react-redux
save
yup





@react-native-community/eslint-config
@types/react-native
eslint
eslint-config-standard
eslint-plugin-import
eslint-plugin-n
eslint-plugin-node
eslint-plugin-promise
eslint-plugin-react
eslint-plugin-react-native
prettier
typescript
